### ISSUE TITLE
Please release your code

### ISSUE THREAD

**Issue by itolPride** [XL2248/IKTN#2]
Hello，I think your paper is good. I have read your paper carefully and found a problem: where is your appendix？I can't find it in your paper.What's more, can you please release the code? I would be very grateful if you release the code.

**Comment by itolPride** [comment]
What tools do you use to generate the  dependency tree？

**Comment by XL2248** [comment]
The appendix is forgotten to upload and code will be released soon. The dependency tree is generated by https://spacy.io/

**Comment by itolPride** [comment]
Thanks for your reply, I am looking forward to your code




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "XLiang"<notifications@github.com&gt;; 
发送时间: 2020年9月16日(星期三) 下午5:26
收件人: "XL2248/IKTN"<IKTN@noreply.github.com&gt;; 
抄送: "潘志豪"<2572298748@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [XL2248/IKTN] Please release your code (#2)





 
The appendix is forgotten to upload and code will be released soon. The dependency tree is generated by https://spacy.io/
