### ISSUE TITLE
能够提供一下  only_ A_ Norm0.5.pkl 或是生成的方式呢？

### ISSUE THREAD

**Issue by YuqiChen4188** [XL2248/IKTN#3]

**Comment by XL2248** [comment]
当前的IKTN这篇工作并没有涉及*.pkl 文件，可以直接注释掉对应部分； 代码中的*.pkl 文件是我们对句法的尝试和探索，如果需要可以参考这个 https://github.com/XL2248/DREGCN 代码里的prepare_data_A.py 和 utils_opinion.py，如果对你有帮助，欢迎star
